version: '2'
services:
    messagingservice-app:
        image: messagingservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://messagingservice-postgresql:5432/messagingservice
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=192.168.26
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=192.168.26
    messagingservice-postgresql:
        extends:
            file: postgresql.yml
            service: messagingservice-postgresql
